# 开发环境profile
server:
  port: 8888
  contextPath: /huahua

mysql:
     host: 140.143.26.129
     port: 3306
redis:
     host: 192.168.80.134
     port: 6379
spring:
  http:
    encoding:
      force: true
  datasource:
    name: huahua
    url: jdbc:mysql://${mysql.host}:${mysql.port}/huahua?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: PHXwlj19901022
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    #Redis连接配置
    RedisProps:
        database: 0
        host: ${redis.host}
        password:
        port: ${redis.port}
        maxActive: 100
        maxIdle: 100
        maxWait: -1
        minIdle: 0
        timeout: 0


#mybatis:
#    type-handlers-package: org.apache.ibatis.type.LocalDateTypeHandler